### ISSUE TITLE
The App can't assign Wan Address to devices

### ISSUE THREAD

**Issue by seyedsalar** [Tribler/trustchain-android#71]
I use two device that run trustchain application but none of them can't take wan address and when i change bootstrap server (enter local address of tablet in phone),"this peer currently not active" was shown.
![Screenshot_20200222-104820](https://user-images.githubusercontent.com/39945203/75329500-f3fbf000-5894-11ea-89cd-e4e424e5d263.png)

**Comment by MattSkala** [comment]
Thanks for reporting the issue. However, note that this project is not maintained anymore. Please check out our new Kotlin implementation: https://github.com/Tribler/kotlin-ipv8

**Comment by seyedsalar** [comment]
Thanks for your comment.
